name: build the image and push to docker hub
on:
  push:
    branches:
      - push_to_docker_hub
jobs:
  build-and-push:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: checkout the code
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: osama3akre/test-image:latest, osama3akre/test-image:${{ github.run_number }}