name: check mode&npm versions
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
    - name: check node version
    - run: node -v
    - run: npm -v