name: check mode&npm versions
on:
  push:
    branches:
      - node-app-1
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node -v
      - run: npm -v
      - uses: actions/checkout@v3
      - run: npm i
      - run: node app.js
