name: build the image and push to docker hub
on:
  push:
    branches:
      - test_file
jobs:
  build-and-push:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: checkout the code
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: build and push php image
        uses: docker/build-push-action@v3
        with:
          context: .
          secrets: |
            "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
          push: true
          tags: erbilcenter/test:${{ github.run_number }}
